import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Section from "@/components/Section";
import Footer from "@/components/Footer"
// import page from "../HTMLpage/page";
// import SidebarLayout from "./HTMLpage/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {/* <Sidebar/> */}
        {/* <Section /> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}